### ISSUE TITLE
Possible to make logo a little more distinct from Polymer logo?

### ISSUE THREAD

**Issue by tjsavage** [StartPolymer/s-elements#1]
Apologies if this is not the right place to post this.

My name is Taylor, I'm the Product Manager of the Polymer project. I love this project and the StartPolymer project overall - it's a killer resource for Polymer developers.

We've heard some [reports](https://github.com/webcomponents/webcomponents.org/issues/783) that particularly on the new webcomponents.org catalog it can be easy to confuse StartPolymer project items from Polymer project items.

Would it be possible to make the StartPolymer logo a little more distinct from the Polymer logo? I could see for example using a different color scheme, or integrating the Polymer logo into a larger more distinct logo, or something else?

**Comment by JosefJezek** [comment]
I change the logo now.
